//! UI interaction via hand raycasts.
//!
//! Provides a raycast-based UI pointing system for VR hands.
//! Tracks hover/press/release state transitions and emits UI interaction events.

use aether_ecs::Entity;

use crate::components::Transform;
use crate::vr::math;

/// Default maximum raycast distance for UI interaction (meters).
const DEFAULT_UI_RAYCAST_MAX_DISTANCE: f32 = 10.0;

/// Default forward direction for hand raycasts (negative Z in hand space).
const DEFAULT_RAY_DIRECTION: [f32; 3] = [0.0, 0.0, -1.0];

/// Result of a UI raycast hit.
#[derive(Debug, Clone, PartialEq)]
pub struct UiHitResult {
    /// World-space hit point on the UI surface.
    pub point: [f32; 3],
    /// Surface normal at the hit point.
    pub normal: [f32; 3],
    /// Distance from ray origin to the hit point.
    pub distance: f32,
    /// The entity representing the UI panel/widget.
    pub entity: Entity,
    /// Optional UV coordinates on the UI surface (if available).
    pub uv: Option<[f32; 2]>,
}

/// Represents the interaction state of a hand with UI.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UiInteractionPhase {
    /// Not interacting with any UI.
    None,
    /// Hovering over a UI element.
    Hover,
    /// Pressing (trigger held) on a UI element.
    Press,
}

/// An event emitted when UI interaction state changes.
#[derive(Debug, Clone, PartialEq)]
pub enum UiInteractionEvent {
    /// Hover began on an entity.
    HoverEnter { entity: Entity, point: [f32; 3] },
    /// Hover ended on an entity.
    HoverExit { entity: Entity },
    /// Press began on an entity.
    PressDown { entity: Entity, point: [f32; 3] },
    /// Press ended on an entity (click completed).
    PressUp { entity: Entity, point: [f32; 3] },
}

/// Configuration for UI raycasting.
#[derive(Debug, Clone, PartialEq)]
pub struct UiRaycastConfig {
    /// Maximum raycast distance.
    pub max_distance: f32,
    /// Ray direction in the hand's local space.
    pub ray_direction_local: [f32; 3],
    /// Offset from hand position for the ray origin (local space).
    pub ray_origin_offset: [f32; 3],
}

impl Default for UiRaycastConfig {
    fn default() -> Self {
        Self {
            max_distance: DEFAULT_UI_RAYCAST_MAX_DISTANCE,
            ray_direction_local: DEFAULT_RAY_DIRECTION,
            ray_origin_offset: [0.0; 3],
        }
    }
}

impl UiRaycastConfig {
    pub fn with_max_distance(mut self, distance: f32) -> Self {
        self.max_distance = distance;
        self
    }

    pub fn with_ray_direction(mut self, direction: [f32; 3]) -> Self {
        self.ray_direction_local = math::normalize(direction);
        self
    }

    pub fn with_origin_offset(mut self, offset: [f32; 3]) -> Self {
        self.ray_origin_offset = offset;
        self
    }

    /// Compute the world-space ray origin and direction from a hand transform.
    pub fn compute_ray(&self, hand_transform: &Transform) -> ([f32; 3], [f32; 3]) {
        let origin = math::add(
            hand_transform.position,
            math::quat_rotate(hand_transform.rotation, self.ray_origin_offset),
        );
        let direction = math::quat_rotate(hand_transform.rotation, self.ray_direction_local);
        (origin, direction)
    }
}

/// Tracks UI interaction state for a single hand.
#[derive(Debug)]
pub struct UiInteractionState {
    config: UiRaycastConfig,
    phase: UiInteractionPhase,
    /// The entity currently being hovered/pressed, if any.
    current_target: Option<Entity>,
    /// The hit point of the current interaction.
    current_hit_point: Option<[f32; 3]>,
    /// Pending events generated by the last update.
    pending_events: Vec<UiInteractionEvent>,
}

impl UiInteractionState {
    /// Create a new UI interaction state with default config.
    pub fn new() -> Self {
        Self {
            config: UiRaycastConfig::default(),
            phase: UiInteractionPhase::None,
            current_target: None,
            current_hit_point: None,
            pending_events: Vec::new(),
        }
    }

    /// Create with a specific configuration.
    pub fn with_config(config: UiRaycastConfig) -> Self {
        Self {
            config,
            phase: UiInteractionPhase::None,
            current_target: None,
            current_hit_point: None,
            pending_events: Vec::new(),
        }
    }

    /// Get the current interaction phase.
    pub fn phase(&self) -> UiInteractionPhase {
        self.phase
    }

    /// Get the current target entity, if any.
    pub fn current_target(&self) -> Option<Entity> {
        self.current_target
    }

    /// Get the configuration.
    pub fn config(&self) -> &UiRaycastConfig {
        &self.config
    }

    /// Compute the ray for the given hand transform.
    pub fn compute_ray(&self, hand_transform: &Transform) -> ([f32; 3], [f32; 3]) {
        self.config.compute_ray(hand_transform)
    }

    /// Update the interaction state with a new raycast hit result and trigger state.
    ///
    /// `hit` is `None` if the ray didn't hit any UI element.
    /// `trigger_pressed` indicates whether the hand's trigger/button is pressed.
    ///
    /// Returns events generated by this update.
    pub fn update(
        &mut self,
        hit: Option<&UiHitResult>,
        trigger_pressed: bool,
    ) -> Vec<UiInteractionEvent> {
        self.pending_events.clear();

        match (hit, self.phase, self.current_target) {
            // Ray hits something, was not interacting before
            (Some(hit_result), UiInteractionPhase::None, _) => {
                self.current_target = Some(hit_result.entity);
                self.current_hit_point = Some(hit_result.point);
                self.pending_events.push(UiInteractionEvent::HoverEnter {
                    entity: hit_result.entity,
                    point: hit_result.point,
                });
                self.phase = UiInteractionPhase::Hover;

                if trigger_pressed {
                    self.pending_events.push(UiInteractionEvent::PressDown {
                        entity: hit_result.entity,
                        point: hit_result.point,
                    });
                    self.phase = UiInteractionPhase::Press;
                }
            }

            // Ray hits something, was hovering
            (Some(hit_result), UiInteractionPhase::Hover, Some(prev_entity))
                if prev_entity == hit_result.entity =>
            {
                // Same entity, update hit point
                self.current_hit_point = Some(hit_result.point);

                if trigger_pressed {
                    self.pending_events.push(UiInteractionEvent::PressDown {
                        entity: hit_result.entity,
                        point: hit_result.point,
                    });
                    self.phase = UiInteractionPhase::Press;
                }
            }

            // Ray hits a different entity while hovering
            (Some(hit_result), UiInteractionPhase::Hover, Some(prev_entity)) => {
                // Exit old, enter new
                self.pending_events.push(UiInteractionEvent::HoverExit {
                    entity: prev_entity,
                });
                self.pending_events.push(UiInteractionEvent::HoverEnter {
                    entity: hit_result.entity,
                    point: hit_result.point,
                });
                self.current_target = Some(hit_result.entity);
                self.current_hit_point = Some(hit_result.point);

                if trigger_pressed {
                    self.pending_events.push(UiInteractionEvent::PressDown {
                        entity: hit_result.entity,
                        point: hit_result.point,
                    });
                    self.phase = UiInteractionPhase::Press;
                }
            }

            // Ray hits something, was pressing
            (Some(hit_result), UiInteractionPhase::Press, Some(prev_entity)) => {
                self.current_hit_point = Some(hit_result.point);

                if !trigger_pressed {
                    // Release
                    self.pending_events.push(UiInteractionEvent::PressUp {
                        entity: prev_entity,
                        point: hit_result.point,
                    });
                    if hit_result.entity == prev_entity {
                        self.phase = UiInteractionPhase::Hover;
                    } else {
                        self.pending_events.push(UiInteractionEvent::HoverExit {
                            entity: prev_entity,
                        });
                        self.pending_events.push(UiInteractionEvent::HoverEnter {
                            entity: hit_result.entity,
                            point: hit_result.point,
                        });
                        self.current_target = Some(hit_result.entity);
                        self.phase = UiInteractionPhase::Hover;
                    }
                }
            }

            // Ray misses, was hovering
            (None, UiInteractionPhase::Hover, Some(prev_entity)) => {
                self.pending_events.push(UiInteractionEvent::HoverExit {
                    entity: prev_entity,
                });
                self.current_target = None;
                self.current_hit_point = None;
                self.phase = UiInteractionPhase::None;
            }

            // Ray misses, was pressing
            (None, UiInteractionPhase::Press, Some(prev_entity)) => {
                self.pending_events.push(UiInteractionEvent::PressUp {
                    entity: prev_entity,
                    point: self.current_hit_point.unwrap_or([0.0; 3]),
                });
                self.pending_events.push(UiInteractionEvent::HoverExit {
                    entity: prev_entity,
                });
                self.current_target = None;
                self.current_hit_point = None;
                self.phase = UiInteractionPhase::None;
            }

            // No hit, already in None state
            (None, UiInteractionPhase::None, _) => {}

            // Catch-all: shouldn't happen but handle gracefully
            _ => {
                self.current_target = None;
                self.current_hit_point = None;
                self.phase = UiInteractionPhase::None;
            }
        }

        self.pending_events.clone()
    }

    /// Reset the interaction state.
    pub fn reset(&mut self) {
        if let Some(entity) = self.current_target {
            match self.phase {
                UiInteractionPhase::Press => {
                    self.pending_events.push(UiInteractionEvent::PressUp {
                        entity,
                        point: self.current_hit_point.unwrap_or([0.0; 3]),
                    });
                    self.pending_events
                        .push(UiInteractionEvent::HoverExit { entity });
                }
                UiInteractionPhase::Hover => {
                    self.pending_events
                        .push(UiInteractionEvent::HoverExit { entity });
                }
                UiInteractionPhase::None => {}
            }
        }
        self.phase = UiInteractionPhase::None;
        self.current_target = None;
        self.current_hit_point = None;
    }

    /// Drain pending events.
    pub fn drain_events(&mut self) -> Vec<UiInteractionEvent> {
        std::mem::take(&mut self.pending_events)
    }
}

impl Default for UiInteractionState {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entity(index: u32) -> Entity {
        unsafe { std::mem::transmute::<(u32, u32), Entity>((index, 0)) }
    }

    fn make_hit(entity_index: u32, point: [f32; 3], distance: f32) -> UiHitResult {
        UiHitResult {
            point,
            normal: [0.0, 0.0, 1.0],
            distance,
            entity: entity(entity_index),
            uv: None,
        }
    }

    // --- UiRaycastConfig tests ---

    #[test]
    fn config_defaults() {
        let c = UiRaycastConfig::default();
        assert_eq!(c.max_distance, DEFAULT_UI_RAYCAST_MAX_DISTANCE);
        assert_eq!(c.ray_direction_local, DEFAULT_RAY_DIRECTION);
        assert_eq!(c.ray_origin_offset, [0.0; 3]);
    }

    #[test]
    fn config_with_max_distance() {
        let c = UiRaycastConfig::default().with_max_distance(20.0);
        assert_eq!(c.max_distance, 20.0);
    }

    #[test]
    fn config_with_ray_direction_normalizes() {
        let c = UiRaycastConfig::default().with_ray_direction([0.0, 0.0, -5.0]);
        let len = math::length(c.ray_direction_local);
        assert!(
            (len - 1.0).abs() < 1e-5,
            "Direction should be normalized: {}",
            len,
        );
    }

    #[test]
    fn config_with_origin_offset() {
        let c = UiRaycastConfig::default().with_origin_offset([0.0, 0.05, 0.0]);
        assert_eq!(c.ray_origin_offset, [0.0, 0.05, 0.0]);
    }

    #[test]
    fn compute_ray_identity_transform() {
        let c = UiRaycastConfig::default();
        let t = Transform {
            position: [1.0, 2.0, 3.0],
            rotation: [0.0, 0.0, 0.0, 1.0],
        };
        let (origin, direction) = c.compute_ray(&t);
        assert_eq!(origin, [1.0, 2.0, 3.0]);
        assert_eq!(direction, [0.0, 0.0, -1.0]);
    }

    #[test]
    fn compute_ray_with_offset() {
        let c = UiRaycastConfig::default().with_origin_offset([0.0, 0.1, 0.0]);
        let t = Transform {
            position: [0.0, 0.0, 0.0],
            rotation: [0.0, 0.0, 0.0, 1.0],
        };
        let (origin, _) = c.compute_ray(&t);
        assert!((origin[1] - 0.1).abs() < 1e-5);
    }

    // --- UiInteractionState tests ---

    #[test]
    fn state_default_is_none() {
        let s = UiInteractionState::new();
        assert_eq!(s.phase(), UiInteractionPhase::None);
        assert!(s.current_target().is_none());
    }

    #[test]
    fn hover_enter_on_first_hit() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        let events = s.update(Some(&hit), false);

        assert_eq!(s.phase(), UiInteractionPhase::Hover);
        assert_eq!(s.current_target().unwrap().index(), 1);
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], UiInteractionEvent::HoverEnter { .. }));
    }

    #[test]
    fn hover_exit_when_ray_misses() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);

        let events = s.update(None, false);
        assert_eq!(s.phase(), UiInteractionPhase::None);
        assert!(s.current_target().is_none());
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], UiInteractionEvent::HoverExit { .. }));
    }

    #[test]
    fn hover_to_different_entity() {
        let mut s = UiInteractionState::new();
        let hit1 = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit1), false);

        let hit2 = make_hit(2, [1.0, 0.0, 5.0], 5.0);
        let events = s.update(Some(&hit2), false);

        assert_eq!(s.phase(), UiInteractionPhase::Hover);
        assert_eq!(s.current_target().unwrap().index(), 2);
        // Should have HoverExit(1) and HoverEnter(2)
        assert_eq!(events.len(), 2);
        assert!(
            matches!(events[0], UiInteractionEvent::HoverExit { entity } if entity.index() == 1)
        );
        assert!(
            matches!(events[1], UiInteractionEvent::HoverEnter { entity, .. } if entity.index() == 2)
        );
    }

    #[test]
    fn press_on_hover() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);

        let events = s.update(Some(&hit), true);
        assert_eq!(s.phase(), UiInteractionPhase::Press);
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], UiInteractionEvent::PressDown { .. }));
    }

    #[test]
    fn release_press() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);
        s.update(Some(&hit), true); // press

        let events = s.update(Some(&hit), false); // release
        assert_eq!(s.phase(), UiInteractionPhase::Hover);
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], UiInteractionEvent::PressUp { .. }));
    }

    #[test]
    fn press_and_immediate_hover_enter() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);

        // First frame: hit + trigger pressed -> HoverEnter + PressDown
        let events = s.update(Some(&hit), true);
        assert_eq!(s.phase(), UiInteractionPhase::Press);
        assert_eq!(events.len(), 2);
        assert!(matches!(events[0], UiInteractionEvent::HoverEnter { .. }));
        assert!(matches!(events[1], UiInteractionEvent::PressDown { .. }));
    }

    #[test]
    fn press_lost_ray() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);
        s.update(Some(&hit), true); // press

        // Ray misses while pressing -> PressUp + HoverExit
        let events = s.update(None, true);
        assert_eq!(s.phase(), UiInteractionPhase::None);
        assert_eq!(events.len(), 2);
        assert!(matches!(events[0], UiInteractionEvent::PressUp { .. }));
        assert!(matches!(events[1], UiInteractionEvent::HoverExit { .. }));
    }

    #[test]
    fn no_events_when_nothing_happening() {
        let mut s = UiInteractionState::new();
        let events = s.update(None, false);
        assert!(events.is_empty());
        assert_eq!(s.phase(), UiInteractionPhase::None);
    }

    #[test]
    fn sustained_hover_same_entity_no_extra_events() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false); // HoverEnter

        // Continue hovering same entity
        let events = s.update(Some(&hit), false);
        assert!(events.is_empty());
        assert_eq!(s.phase(), UiInteractionPhase::Hover);
    }

    #[test]
    fn hit_result_with_uv() {
        let hit = UiHitResult {
            point: [0.0, 0.0, 5.0],
            normal: [0.0, 0.0, 1.0],
            distance: 5.0,
            entity: entity(1),
            uv: Some([0.5, 0.5]),
        };
        assert_eq!(hit.uv, Some([0.5, 0.5]));
    }

    #[test]
    fn reset_generates_exit_events() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);
        s.update(Some(&hit), true); // press

        s.reset();
        assert_eq!(s.phase(), UiInteractionPhase::None);
        assert!(s.current_target().is_none());
    }

    #[test]
    fn drain_events_clears() {
        let mut s = UiInteractionState::new();
        let hit = make_hit(1, [0.0, 0.0, 5.0], 5.0);
        s.update(Some(&hit), false);

        let events = s.drain_events();
        assert!(!events.is_empty());

        let events2 = s.drain_events();
        assert!(events2.is_empty());
    }

    #[test]
    fn phase_equality() {
        assert_eq!(UiInteractionPhase::None, UiInteractionPhase::None);
        assert_ne!(UiInteractionPhase::None, UiInteractionPhase::Hover);
        assert_ne!(UiInteractionPhase::Hover, UiInteractionPhase::Press);
    }
}
