/// Moderation report types for internal tracking and escalation.
use crate::severity::ContentSeverity;

/// Severity levels for moderation reports (internal use).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModerationSeverity {
    /// Information only, no action needed.
    Informational,
    /// Warning that may require attention.
    Warning,
    /// Critical issue requiring immediate action.
    Critical,
}

impl From<ContentSeverity> for ModerationSeverity {
    fn from(severity: ContentSeverity) -> Self {
        match severity {
            ContentSeverity::Clean | ContentSeverity::Low => ModerationSeverity::Informational,
            ContentSeverity::Medium | ContentSeverity::High => ModerationSeverity::Warning,
            ContentSeverity::Critical => ModerationSeverity::Critical,
        }
    }
}

/// An internal moderation report generated by the system.
#[derive(Debug, Clone)]
pub struct ModerationReport {
    /// Unique report identifier.
    pub report_id: String,
    /// Content being reported on.
    pub artifact_id: String,
    /// Details about the moderation finding.
    pub details: String,
    /// Severity of the report.
    pub severity: ModerationSeverity,
}

impl ModerationReport {
    pub fn new(
        report_id: String,
        artifact_id: String,
        details: String,
        severity: ModerationSeverity,
    ) -> Self {
        Self {
            report_id,
            artifact_id,
            details,
            severity,
        }
    }
}

/// A case that tracks escalated moderation reports.
#[derive(Debug, Clone)]
pub struct ReportCase {
    /// Unique case identifier.
    pub case_id: String,
    /// Report that triggered this case.
    pub report_id: String,
    /// Whether this case has been escalated to senior staff.
    pub escalated: bool,
    /// Optional notes from the reviewer.
    pub notes: Option<String>,
}

impl ReportCase {
    pub fn new(case_id: String, report_id: String) -> Self {
        Self {
            case_id,
            report_id,
            escalated: false,
            notes: None,
        }
    }

    /// Escalate this case to senior moderators.
    pub fn escalate(&mut self) {
        self.escalated = true;
    }

    /// Add reviewer notes to this case.
    pub fn add_notes(&mut self, notes: String) {
        self.notes = Some(notes);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_moderation_severity_from_clean() {
        assert_eq!(
            ModerationSeverity::from(ContentSeverity::Clean),
            ModerationSeverity::Informational
        );
    }

    #[test]
    fn test_moderation_severity_from_low() {
        assert_eq!(
            ModerationSeverity::from(ContentSeverity::Low),
            ModerationSeverity::Informational
        );
    }

    #[test]
    fn test_moderation_severity_from_medium() {
        assert_eq!(
            ModerationSeverity::from(ContentSeverity::Medium),
            ModerationSeverity::Warning
        );
    }

    #[test]
    fn test_moderation_severity_from_high() {
        assert_eq!(
            ModerationSeverity::from(ContentSeverity::High),
            ModerationSeverity::Warning
        );
    }

    #[test]
    fn test_moderation_severity_from_critical() {
        assert_eq!(
            ModerationSeverity::from(ContentSeverity::Critical),
            ModerationSeverity::Critical
        );
    }

    #[test]
    fn test_moderation_report_new() {
        let report = ModerationReport::new(
            "report-1".to_string(),
            "artifact-1".to_string(),
            "suspicious content".to_string(),
            ModerationSeverity::Warning,
        );
        assert_eq!(report.report_id, "report-1");
        assert_eq!(report.artifact_id, "artifact-1");
        assert_eq!(report.severity, ModerationSeverity::Warning);
    }

    #[test]
    fn test_report_case_new() {
        let case = ReportCase::new("case-1".to_string(), "report-1".to_string());
        assert!(!case.escalated);
        assert!(case.notes.is_none());
    }

    #[test]
    fn test_report_case_escalate() {
        let mut case = ReportCase::new("case-1".to_string(), "report-1".to_string());
        case.escalate();
        assert!(case.escalated);
    }

    #[test]
    fn test_report_case_add_notes() {
        let mut case = ReportCase::new("case-1".to_string(), "report-1".to_string());
        case.add_notes("reviewed and confirmed".to_string());
        assert_eq!(case.notes.as_deref(), Some("reviewed and confirmed"));
    }
}
